import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import cesium from 'vite-plugin-cesium';
import fs from 'node:fs';
import path from 'path';

/**
 * MediaPipe wasm runtime for hand tracking, served same-origin from
 * /vendor/mediapipe/* — single-sourced straight out of node_modules, exactly
 * like the demo bundle below: the runtime is ~34 MB across the SIMD/module/
 * nosimd variants, so it must never be committed or bundled. The hand model
 * itself (/models/hand_landmarker.task) IS committed, since it is a stable
 * 8 MB artifact with no install step.
 */
const MEDIAPIPE_WASM_DIR = path.resolve(
  __dirname,
  './node_modules/@mediapipe/tasks-vision/wasm',
);
function serveHandTrackingWasm(): Plugin {
  const send = (file: string, res: import('node:http').ServerResponse) => {
    fs.readFile(path.join(MEDIAPIPE_WASM_DIR, file), (err, buf) => {
      if (err) {
        res.statusCode = 404;
        res.end('not found');
        return;
      }
      res.setHeader(
        'Content-Type',
        file.endsWith('.wasm') ? 'application/wasm' : 'text/javascript; charset=utf-8',
      );
      res.end(buf);
    });
  };
  return {
    name: 'serve-mediapipe-wasm',
    // Dev server middleware.
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const p = (req.url || '').split('?')[0];
        if (!p.startsWith('/vendor/mediapipe/')) return next();
        const file = path.basename(p);
        if (!/^vision_wasm[a-z_]*_internal\.(js|wasm)$/.test(file)) return next();
        send(file, res);
      });
    },
    // Production build: emit the runtime into dist (copied, never bundled —
    // the loader fetches these paths at runtime).
    closeBundle() {
      const out = path.resolve(__dirname, 'dist/vendor/mediapipe');
      fs.mkdirSync(out, { recursive: true });
      for (const f of fs.readdirSync(MEDIAPIPE_WASM_DIR)) {
        fs.copyFileSync(path.join(MEDIAPIPE_WASM_DIR, f), path.join(out, f));
      }
    },
  };
}

/** Precomputed sandbox demo bundle (single source of truth for /demo/). */
const DEMO_FILE = path.resolve(__dirname, '../backend/app/sandbox/demo_cache/tehri_demo.json');

export default defineConfig({
  plugins: [
    react(),
    cesium(),
    // Precomputed sandbox demo bundle: generated by
    // backend/app/sandbox/make_demo.py into backend/app/sandbox/demo_cache/.
    // Served statically (single source, no committed copy) so the "Offline
    // demo" works with no backend process and no API keys.
    {
      name: 'serve-precomputed-demo',
      configureServer(server) {
        server.middlewares.use((req, res, next) => {
          if ((req.url || '').split('?')[0] !== '/demo/tehri_demo.json') return next();
          fs.readFile(DEMO_FILE, (err, buf) => {
            if (err) return next();
            res.setHeader('Content-Type', 'application/json');
            res.end(buf);
          });
        });
      },
      // The dev middleware is dev-only, so a production build used to have no
      // /demo/ route at all: the offline demo fell through to an API call that
      // needs a running backend, i.e. the one keyless path stopped working.
      // Emit the same file into the build output instead of committing a copy.
      closeBundle() {
        if (!fs.existsSync(DEMO_FILE)) {
          this.warn(`offline demo bundle missing at ${DEMO_FILE} — /demo/ will 404 in this build`);
          return;
        }
        const out = path.resolve(__dirname, 'dist/demo');
        fs.mkdirSync(out, { recursive: true });
        fs.copyFileSync(DEMO_FILE, path.join(out, 'tehri_demo.json'));
      },
    },
    serveHandTrackingWasm(),
    // CORS middleware so other local origins can fetch /india-dams.geojson
    {
      name: 'cors-headers',
      configureServer(server) {
        server.middlewares.use((_req, res, next) => {
          res.setHeader('Access-Control-Allow-Origin', '*');
          res.setHeader('Access-Control-Allow-Methods', 'GET');
          next();
        });
      },
    },
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'http://localhost:8000',
        changeOrigin: true,
      },
      // Lets the keepalive hit backend /health through the dev server too.
      '/health': {
        target: 'http://localhost:8000',
        changeOrigin: true,
      },
      '/ws': {
        target: 'ws://localhost:8000',
        ws: true,
      },
    },
  },
});
