import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import cesium from 'vite-plugin-cesium';
import fs from 'node:fs';
import path from 'path';

export default defineConfig({
  plugins: [
    react(),
    cesium(),
    // Precomputed sandbox demo bundle: generated by
    // backend/app/sandbox/make_demo.py into backend/app/sandbox/demo_cache/.
    // Served statically here (single source, no copied artifact) so the
    // "Offline demo" works with no backend process and no API keys.
    {
      name: 'serve-precomputed-demo',
      configureServer(server) {
        const demoFile = path.resolve(__dirname, '../backend/app/sandbox/demo_cache/tehri_demo.json');
        server.middlewares.use((req, res, next) => {
          if ((req.url || '').split('?')[0] !== '/demo/tehri_demo.json') return next();
          fs.readFile(demoFile, (err, buf) => {
            if (err) return next();
            res.setHeader('Content-Type', 'application/json');
            res.end(buf);
          });
        });
      },
    },
    // CORS middleware so GeoLibre (localhost:5175) can fetch /india-dams.geojson
    {
      name: 'cors-headers',
      configureServer(server) {
        server.middlewares.use((_req, res, next) => {
          res.setHeader('Access-Control-Allow-Origin', '*');
          res.setHeader('Access-Control-Allow-Methods', 'GET');
          next();
        });
      },
    },
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'http://localhost:8000',
        changeOrigin: true,
      },
      // Lets the keepalive hit backend /health through the dev server too.
      '/health': {
        target: 'http://localhost:8000',
        changeOrigin: true,
      },
      '/ws': {
        target: 'ws://localhost:8000',
        ws: true,
      },
    },
  },
});
