import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import cesium from 'vite-plugin-cesium';
import fs from 'node:fs';
import path from 'path';

/** Precomputed sandbox demo bundle (single source of truth for /demo/). */
const DEMO_FILE = path.resolve(__dirname, '../backend/app/sandbox/demo_cache/tehri_demo.json');

export default defineConfig({
  plugins: [
    react(),
    cesium(),
    // Precomputed sandbox demo bundle: generated by
    // backend/app/sandbox/make_demo.py into backend/app/sandbox/demo_cache/.
    // Served statically (single source, no committed copy) so the "Offline
    // demo" works with no backend process and no API keys.
    {
      name: 'serve-precomputed-demo',
      configureServer(server) {
        server.middlewares.use((req, res, next) => {
          if ((req.url || '').split('?')[0] !== '/demo/tehri_demo.json') return next();
          fs.readFile(DEMO_FILE, (err, buf) => {
            if (err) return next();
            res.setHeader('Content-Type', 'application/json');
            res.end(buf);
          });
        });
      },
      // The dev middleware is dev-only, so a production build used to have no
      // /demo/ route at all: the offline demo fell through to an API call that
      // needs a running backend, i.e. the one keyless path stopped working.
      // Emit the same file into the build output instead of committing a copy.
      closeBundle() {
        if (!fs.existsSync(DEMO_FILE)) {
          this.warn(`offline demo bundle missing at ${DEMO_FILE} — /demo/ will 404 in this build`);
          return;
        }
        const out = path.resolve(__dirname, 'dist/demo');
        fs.mkdirSync(out, { recursive: true });
        fs.copyFileSync(DEMO_FILE, path.join(out, 'tehri_demo.json'));
      },
    },
    // CORS middleware so other local origins can fetch /india-dams.geojson
    {
      name: 'cors-headers',
      configureServer(server) {
        server.middlewares.use((_req, res, next) => {
          res.setHeader('Access-Control-Allow-Origin', '*');
          res.setHeader('Access-Control-Allow-Methods', 'GET');
          next();
        });
      },
    },
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'http://localhost:8000',
        changeOrigin: true,
      },
      // Lets the keepalive hit backend /health through the dev server too.
      '/health': {
        target: 'http://localhost:8000',
        changeOrigin: true,
      },
      '/ws': {
        target: 'ws://localhost:8000',
        ws: true,
      },
    },
  },
});
