"""
Demo seed snapshot — REAL recorded data, embedded for ephemeral deploys.

Render's free tier has no persistent disk, so the run ledger / alert store
built up during a session vanish on every redeploy, leaving the Alert
Console and Report Generator empty in the live demo. This module embeds the
genuine records from the development session (every figure was really
computed by the sandbox/impact engine and every alert really went through
the human approve → dispatch gates) and re-applies them at startup — but
ONLY into empty stores, so live usage is never overwritten.

Refresh the snapshot after a meaningful local session:

    python scripts/make_demo_seed.py
"""

RUN_LEDGER_ROWS = [{'id': '13378859-4caa-4947-9cb5-d59b5f39f095',
  'run_kind': 'sandbox',
  'dam_id': 'd52',
  'dam_name': 'Idukki Dam',
  'case': 'test',
  'mode': 'REAL COMPUTED SIMULATION',
  'engine': 'sandbox-diffusive-screening-v2',
  'created_at': '2026-09-27T06:52:13Z',
  'created_ts': 1790491933.7957706,
  'grids_present': True,
  'scenario': {'dam_id': 'd52',
               'label': 'test',
               'reservoir_level_m': 100.0,
               'breach_location': 'dam',
               'breach_width_m': 200.0,
               'breach_depth_m': 10.0,
               'breach_severity': 'major',
               'initial_release_m3': 2000000.0,
               'roughness': 0.05,
               'rainfall_factor': 0.0,
               'duration_min': 60.0,
               'timestep_s': 60.0,
               'seed': 7,
               'breach_formation_min': None},
  'summary': {'flooded_area_km2': 2.861,
              'flooded_cells': 66,
              'max_depth_anywhere_m': 4.15,
              'max_depth_note': 'Peak outside the breach inflow zone (breach + inflow trail)',
              'assets_evaluated': 146,
              'assets_critical': 0,
              'earliest_asset_arrival_min': None,
              'volume_in_m3': 3300411.8,
              'volume_stored_m3': 3300411.8,
              'steps_used': 60,
              'sim_minutes': 60.0,
              'timesteps': 12,
              'severity_band': 'VERY HIGH',
              'severity_note': 'Heuristic screening band (depth/area/critical count), NOT a '
                               'certified rating',
              'model': 'sandbox-diffusive-screening-v2 (D8 channel-conditioned; NOT hydrodynamics)',
              'peak_discharge_m3s': 1533.6,
              'time_to_peak_min': 11.0,
              'hydrograph_volume_m3': 2000000.0}},
 {'id': '330927d8-7f1f-487a-b59c-755e9dbff837',
  'run_kind': 'sandbox',
  'dam_id': 'd4',
  'dam_name': 'Tehri Dam',
  'case': 'test',
  'mode': 'REAL COMPUTED SIMULATION',
  'engine': 'sandbox-diffusive-screening-v2',
  'created_at': '2026-09-27T06:52:12Z',
  'created_ts': 1790491932.3232996,
  'grids_present': True,
  'scenario': {'dam_id': 'd4',
               'label': 'test',
               'reservoir_level_m': 100.0,
               'breach_location': 'dam',
               'breach_width_m': 200.0,
               'breach_depth_m': 10.0,
               'breach_severity': 'major',
               'initial_release_m3': 2000000.0,
               'roughness': 0.05,
               'rainfall_factor': 0.0,
               'duration_min': 60.0,
               'timestep_s': 60.0,
               'seed': 7,
               'breach_formation_min': None},
  'summary': {'flooded_area_km2': 5.386,
              'flooded_cells': 124,
              'max_depth_anywhere_m': 4.69,
              'max_depth_note': 'Peak outside the breach inflow zone (breach + inflow trail)',
              'assets_evaluated': 200,
              'assets_critical': 2,
              'earliest_asset_arrival_min': 0.0,
              'volume_in_m3': 3303131.6,
              'volume_stored_m3': 3303131.6,
              'steps_used': 60,
              'sim_minutes': 60.0,
              'timesteps': 12,
              'severity_band': 'VERY HIGH',
              'severity_note': 'Heuristic screening band (depth/area/critical count), NOT a '
                               'certified rating',
              'model': 'sandbox-diffusive-screening-v2 (D8 channel-conditioned; NOT hydrodynamics)',
              'peak_discharge_m3s': 1533.6,
              'time_to_peak_min': 11.0,
              'hydrograph_volume_m3': 2000000.0}},
 {'id': '1f07ce1d-bfd4-46b4-abc3-9fa6dc8435f1',
  'run_kind': 'sandbox',
  'dam_id': 'd4',
  'dam_name': 'Tehri Dam',
  'case': 'test',
  'mode': 'REAL COMPUTED SIMULATION',
  'engine': 'sandbox-diffusive-screening-v2',
  'created_at': '2026-09-27T06:52:11Z',
  'created_ts': 1790491931.0683086,
  'grids_present': True,
  'scenario': {'dam_id': 'd4',
               'label': 'test',
               'reservoir_level_m': 100.0,
               'breach_location': 'dam',
               'breach_width_m': 200.0,
               'breach_depth_m': 10.0,
               'breach_severity': 'major',
               'initial_release_m3': 2000000.0,
               'roughness': 0.05,
               'rainfall_factor': 0.0,
               'duration_min': 60.0,
               'timestep_s': 60.0,
               'seed': 7,
               'breach_formation_min': None},
  'summary': {'flooded_area_km2': 5.386,
              'flooded_cells': 124,
              'max_depth_anywhere_m': 4.69,
              'max_depth_note': 'Peak outside the breach inflow zone (breach + inflow trail)',
              'assets_evaluated': 200,
              'assets_critical': 2,
              'earliest_asset_arrival_min': 0.0,
              'volume_in_m3': 3303131.6,
              'volume_stored_m3': 3303131.6,
              'steps_used': 60,
              'sim_minutes': 60.0,
              'timesteps': 12,
              'severity_band': 'VERY HIGH',
              'severity_note': 'Heuristic screening band (depth/area/critical count), NOT a '
                               'certified rating',
              'model': 'sandbox-diffusive-screening-v2 (D8 channel-conditioned; NOT hydrodynamics)',
              'peak_discharge_m3s': 1533.6,
              'time_to_peak_min': 11.0,
              'hydrograph_volume_m3': 2000000.0}},
 {'id': '9a6f6bb2-ff7e-468f-aa9a-021bb7b95cea',
  'run_kind': 'impact',
  'dam_id': 'd4',
  'dam_name': 'Fake Dam',
  'case': 'worst',
  'mode': 'REAL COMPUTED SIMULATION (screening model) — impact figures are modelled estimates',
  'engine': 'sandbox-diffusive-screening-v1',
  'created_at': '2026-09-27T06:52:09Z',
  'created_ts': 1790491929.8842726,
  'grids_present': False,
  'scenario': {'dam_id': 'd4',
               'label': 'worst',
               'reservoir_level_m': 71.25,
               'breach_location': 'dam',
               'breach_width_m': 200.0,
               'breach_depth_m': 45.0,
               'breach_severity': 'full',
               'initial_release_m3': 120000000.0,
               'roughness': 0.03,
               'rainfall_factor': 2.5,
               'duration_min': 180.0,
               'timestep_s': 60.0,
               'seed': 7,
               'breach_formation_min': None},
  'summary': {'overall_risk': 'LOW',
              'flooded_area_km2': 10.26,
              'settlements_assessed': 1,
              'settlements_inundated': 0,
              'settlements_at_risk': 0,
              'settlements_high_or_extreme': 0,
              'critical_assets_exposed': 0,
              'priority_counts': {'LOW': 1, 'MEDIUM': 0, 'HIGH': 0, 'CRITICAL': 0},
              'population_exposed': {'low': 0,
                                     'mid': 0,
                                     'high': 0,
                                     'basis': 'modelled',
                                     'basis_note': 'sum of per-settlement exposure (spread already '
                                                   'applied)'},
              'population_displaced': {'low': 0, 'mid': 0, 'high': 0, 'basis': 'modelled'},
              'people_protected': {'low': 0, 'mid': 0, 'high': 0},
              'damage': {'low_inr': 23841675,
                         'mid_inr': 36679500,
                         'high_inr': 49517325,
                         'basis': 'modelled',
                         'basis_note': 'sum of per-settlement loss + assumed agricultural share of '
                                       'the footprint'},
              'damage_breakdown': {'residential_inr': 0,
                                   'commercial_inr': 0,
                                   'infrastructure_inr': 0,
                                   'agriculture_inr': 36679500},
              'avoided': {'low_inr': 0,
                          'mid_inr': 0,
                          'high_inr': 0,
                          'basis': 'modelled',
                          'basis_note': 'estimated potential saving — early action reduces, never '
                                        'eliminates, damage'},
              'residual_damage': {'low_inr': 23841675, 'mid_inr': 36679500, 'high_inr': 49517325},
              'agriculture': {'low_inr': 23841675,
                              'mid_inr': 36679500,
                              'high_inr': 49517325,
                              'basis': 'modelled',
                              'basis_note': '5.643 km² of the modelled inundation footprint × 55% '
                                            'assumed cropland/pasture share × ₹65,000/ha',
                              'area_km2': 5.643},
              'peak_depth_m': 218.79,
              'earliest_arrival_min': None}},
 {'id': '97b89436-e57d-4baf-9a1b-bd4e6c82f58b',
  'run_kind': 'sandbox',
  'dam_id': 'd52',
  'dam_name': 'Idukki Dam',
  'case': 'test',
  'mode': 'REAL COMPUTED SIMULATION',
  'engine': 'sandbox-diffusive-screening-v2',
  'created_at': '2026-09-27T06:31:01Z',
  'created_ts': 1790490661.9503362,
  'grids_present': True,
  'scenario': {'dam_id': 'd52',
               'label': 'test',
               'reservoir_level_m': 100.0,
               'breach_location': 'dam',
               'breach_width_m': 200.0,
               'breach_depth_m': 10.0,
               'breach_severity': 'major',
               'initial_release_m3': 2000000.0,
               'roughness': 0.05,
               'rainfall_factor': 0.0,
               'duration_min': 60.0,
               'timestep_s': 60.0,
               'seed': 7,
               'breach_formation_min': None},
  'summary': {'flooded_area_km2': 2.861,
              'flooded_cells': 66,
              'max_depth_anywhere_m': 4.15,
              'max_depth_note': 'Peak outside the breach inflow zone (breach + inflow trail)',
              'assets_evaluated': 146,
              'assets_critical': 0,
              'earliest_asset_arrival_min': None,
              'volume_in_m3': 3300411.8,
              'volume_stored_m3': 3300411.8,
              'steps_used': 60,
              'sim_minutes': 60.0,
              'timesteps': 12,
              'severity_band': 'VERY HIGH',
              'severity_note': 'Heuristic screening band (depth/area/critical count), NOT a '
                               'certified rating',
              'model': 'sandbox-diffusive-screening-v2 (D8 channel-conditioned; NOT hydrodynamics)',
              'peak_discharge_m3s': 1533.6,
              'time_to_peak_min': 11.0,
              'hydrograph_volume_m3': 2000000.0}},
 {'id': 'c63b803a-d629-47e2-b296-cee284be854a',
  'run_kind': 'sandbox',
  'dam_id': 'd4',
  'dam_name': 'Tehri Dam',
  'case': 'test',
  'mode': 'REAL COMPUTED SIMULATION',
  'engine': 'sandbox-diffusive-screening-v2',
  'created_at': '2026-09-27T06:31:00Z',
  'created_ts': 1790490660.541572,
  'grids_present': True,
  'scenario': {'dam_id': 'd4',
               'label': 'test',
               'reservoir_level_m': 100.0,
               'breach_location': 'dam',
               'breach_width_m': 200.0,
               'breach_depth_m': 10.0,
               'breach_severity': 'major',
               'initial_release_m3': 2000000.0,
               'roughness': 0.05,
               'rainfall_factor': 0.0,
               'duration_min': 60.0,
               'timestep_s': 60.0,
               'seed': 7,
               'breach_formation_min': None},
  'summary': {'flooded_area_km2': 5.386,
              'flooded_cells': 124,
              'max_depth_anywhere_m': 4.69,
              'max_depth_note': 'Peak outside the breach inflow zone (breach + inflow trail)',
              'assets_evaluated': 200,
              'assets_critical': 2,
              'earliest_asset_arrival_min': 0.0,
              'volume_in_m3': 3303131.6,
              'volume_stored_m3': 3303131.6,
              'steps_used': 60,
              'sim_minutes': 60.0,
              'timesteps': 12,
              'severity_band': 'VERY HIGH',
              'severity_note': 'Heuristic screening band (depth/area/critical count), NOT a '
                               'certified rating',
              'model': 'sandbox-diffusive-screening-v2 (D8 channel-conditioned; NOT hydrodynamics)',
              'peak_discharge_m3s': 1533.6,
              'time_to_peak_min': 11.0,
              'hydrograph_volume_m3': 2000000.0}},
 {'id': 'c9668d61-e97c-415f-94e3-764f0c245359',
  'run_kind': 'sandbox',
  'dam_id': 'd4',
  'dam_name': 'Tehri Dam',
  'case': 'test',
  'mode': 'REAL COMPUTED SIMULATION',
  'engine': 'sandbox-diffusive-screening-v2',
  'created_at': '2026-09-27T06:30:59Z',
  'created_ts': 1790490659.2711735,
  'grids_present': True,
  'scenario': {'dam_id': 'd4',
               'label': 'test',
               'reservoir_level_m': 100.0,
               'breach_location': 'dam',
               'breach_width_m': 200.0,
               'breach_depth_m': 10.0,
               'breach_severity': 'major',
               'initial_release_m3': 2000000.0,
               'roughness': 0.05,
               'rainfall_factor': 0.0,
               'duration_min': 60.0,
               'timestep_s': 60.0,
               'seed': 7,
               'breach_formation_min': None},
  'summary': {'flooded_area_km2': 5.386,
              'flooded_cells': 124,
              'max_depth_anywhere_m': 4.69,
              'max_depth_note': 'Peak outside the breach inflow zone (breach + inflow trail)',
              'assets_evaluated': 200,
              'assets_critical': 2,
              'earliest_asset_arrival_min': 0.0,
              'volume_in_m3': 3303131.6,
              'volume_stored_m3': 3303131.6,
              'steps_used': 60,
              'sim_minutes': 60.0,
              'timesteps': 12,
              'severity_band': 'VERY HIGH',
              'severity_note': 'Heuristic screening band (depth/area/critical count), NOT a '
                               'certified rating',
              'model': 'sandbox-diffusive-screening-v2 (D8 channel-conditioned; NOT hydrodynamics)',
              'peak_discharge_m3s': 1533.6,
              'time_to_peak_min': 11.0,
              'hydrograph_volume_m3': 2000000.0}},
 {'id': 'f21c43cd-265e-45d3-8d89-3b59aed72396',
  'run_kind': 'impact',
  'dam_id': 'd4',
  'dam_name': 'Fake Dam',
  'case': 'worst',
  'mode': 'REAL COMPUTED SIMULATION (screening model) — impact figures are modelled estimates',
  'engine': 'sandbox-diffusive-screening-v1',
  'created_at': '2026-09-27T06:30:57Z',
  'created_ts': 1790490657.5518103,
  'grids_present': False,
  'scenario': {'dam_id': 'd4',
               'label': 'worst',
               'reservoir_level_m': 71.25,
               'breach_location': 'dam',
               'breach_width_m': 200.0,
               'breach_depth_m': 45.0,
               'breach_severity': 'full',
               'initial_release_m3': 120000000.0,
               'roughness': 0.03,
               'rainfall_factor': 2.5,
               'duration_min': 180.0,
               'timestep_s': 60.0,
               'seed': 7,
               'breach_formation_min': None},
  'summary': {'overall_risk': 'LOW',
              'flooded_area_km2': 10.26,
              'settlements_assessed': 1,
              'settlements_inundated': 0,
              'settlements_at_risk': 0,
              'settlements_high_or_extreme': 0,
              'critical_assets_exposed': 0,
              'priority_counts': {'LOW': 1, 'MEDIUM': 0, 'HIGH': 0, 'CRITICAL': 0},
              'population_exposed': {'low': 0,
                                     'mid': 0,
                                     'high': 0,
                                     'basis': 'modelled',
                                     'basis_note': 'sum of per-settlement exposure (spread already '
                                                   'applied)'},
              'population_displaced': {'low': 0, 'mid': 0, 'high': 0, 'basis': 'modelled'},
              'people_protected': {'low': 0, 'mid': 0, 'high': 0},
              'damage': {'low_inr': 23841675,
                         'mid_inr': 36679500,
                         'high_inr': 49517325,
                         'basis': 'modelled',
                         'basis_note': 'sum of per-settlement loss + assumed agricultural share of '
                                       'the footprint'},
              'damage_breakdown': {'residential_inr': 0,
                                   'commercial_inr': 0,
                                   'infrastructure_inr': 0,
                                   'agriculture_inr': 36679500},
              'avoided': {'low_inr': 0,
                          'mid_inr': 0,
                          'high_inr': 0,
                          'basis': 'modelled',
                          'basis_note': 'estimated potential saving — early action reduces, never '
                                        'eliminates, damage'},
              'residual_damage': {'low_inr': 23841675, 'mid_inr': 36679500, 'high_inr': 49517325},
              'agriculture': {'low_inr': 23841675,
                              'mid_inr': 36679500,
                              'high_inr': 49517325,
                              'basis': 'modelled',
                              'basis_note': '5.643 km² of the modelled inundation footprint × 55% '
                                            'assumed cropland/pasture share × ₹65,000/ha',
                              'area_km2': 5.643},
              'peak_depth_m': 218.79,
              'earliest_arrival_min': None}},
 {'id': '746f69b7-d55f-425d-8c7d-ad8111434318',
  'run_kind': 'sandbox',
  'dam_id': 'd52',
  'dam_name': 'Idukki Dam',
  'case': 'test',
  'mode': 'REAL COMPUTED SIMULATION',
  'engine': 'sandbox-diffusive-screening-v2',
  'created_at': '2026-09-26T08:43:23Z',
  'created_ts': 1790412203.0953846,
  'grids_present': True,
  'scenario': {'dam_id': 'd52',
               'label': 'test',
               'reservoir_level_m': 100.0,
               'breach_location': 'dam',
               'breach_width_m': 200.0,
               'breach_depth_m': 10.0,
               'breach_severity': 'major',
               'initial_release_m3': 2000000.0,
               'roughness': 0.05,
               'rainfall_factor': 0.0,
               'duration_min': 60.0,
               'timestep_s': 60.0,
               'seed': 7,
               'breach_formation_min': None},
  'summary': {'flooded_area_km2': 2.861,
              'flooded_cells': 66,
              'max_depth_anywhere_m': 4.15,
              'max_depth_note': 'Peak outside the breach inflow zone (breach + inflow trail)',
              'assets_evaluated': 146,
              'assets_critical': 0,
              'earliest_asset_arrival_min': None,
              'volume_in_m3': 3300411.8,
              'volume_stored_m3': 3300411.8,
              'steps_used': 60,
              'sim_minutes': 60.0,
              'timesteps': 12,
              'severity_band': 'VERY HIGH',
              'severity_note': 'Heuristic screening band (depth/area/critical count), NOT a '
                               'certified rating',
              'model': 'sandbox-diffusive-screening-v2 (D8 channel-conditioned; NOT hydrodynamics)',
              'peak_discharge_m3s': 1533.6,
              'time_to_peak_min': 11.0,
              'hydrograph_volume_m3': 2000000.0}},
 {'id': '3c337931-249c-405d-8c6d-5b37a48b6dc3',
  'run_kind': 'sandbox',
  'dam_id': 'd4',
  'dam_name': 'Tehri Dam',
  'case': 'test',
  'mode': 'REAL COMPUTED SIMULATION',
  'engine': 'sandbox-diffusive-screening-v2',
  'created_at': '2026-09-26T08:43:21Z',
  'created_ts': 1790412201.7787387,
  'grids_present': True,
  'scenario': {'dam_id': 'd4',
               'label': 'test',
               'reservoir_level_m': 100.0,
               'breach_location': 'dam',
               'breach_width_m': 200.0,
               'breach_depth_m': 10.0,
               'breach_severity': 'major',
               'initial_release_m3': 2000000.0,
               'roughness': 0.05,
               'rainfall_factor': 0.0,
               'duration_min': 60.0,
               'timestep_s': 60.0,
               'seed': 7,
               'breach_formation_min': None},
  'summary': {'flooded_area_km2': 5.386,
              'flooded_cells': 124,
              'max_depth_anywhere_m': 4.69,
              'max_depth_note': 'Peak outside the breach inflow zone (breach + inflow trail)',
              'assets_evaluated': 200,
              'assets_critical': 2,
              'earliest_asset_arrival_min': 0.0,
              'volume_in_m3': 3303131.6,
              'volume_stored_m3': 3303131.6,
              'steps_used': 60,
              'sim_minutes': 60.0,
              'timesteps': 12,
              'severity_band': 'VERY HIGH',
              'severity_note': 'Heuristic screening band (depth/area/critical count), NOT a '
                               'certified rating',
              'model': 'sandbox-diffusive-screening-v2 (D8 channel-conditioned; NOT hydrodynamics)',
              'peak_discharge_m3s': 1533.6,
              'time_to_peak_min': 11.0,
              'hydrograph_volume_m3': 2000000.0}},
 {'id': '36a74136-6ac2-448b-8a77-5f2126c7f060',
  'run_kind': 'sandbox',
  'dam_id': 'd4',
  'dam_name': 'Tehri Dam',
  'case': 'test',
  'mode': 'REAL COMPUTED SIMULATION',
  'engine': 'sandbox-diffusive-screening-v2',
  'created_at': '2026-09-26T08:43:20Z',
  'created_ts': 1790412200.5346568,
  'grids_present': True,
  'scenario': {'dam_id': 'd4',
               'label': 'test',
               'reservoir_level_m': 100.0,
               'breach_location': 'dam',
               'breach_width_m': 200.0,
               'breach_depth_m': 10.0,
               'breach_severity': 'major',
               'initial_release_m3': 2000000.0,
               'roughness': 0.05,
               'rainfall_factor': 0.0,
               'duration_min': 60.0,
               'timestep_s': 60.0,
               'seed': 7,
               'breach_formation_min': None},
  'summary': {'flooded_area_km2': 5.386,
              'flooded_cells': 124,
              'max_depth_anywhere_m': 4.69,
              'max_depth_note': 'Peak outside the breach inflow zone (breach + inflow trail)',
              'assets_evaluated': 200,
              'assets_critical': 2,
              'earliest_asset_arrival_min': 0.0,
              'volume_in_m3': 3303131.6,
              'volume_stored_m3': 3303131.6,
              'steps_used': 60,
              'sim_minutes': 60.0,
              'timesteps': 12,
              'severity_band': 'VERY HIGH',
              'severity_note': 'Heuristic screening band (depth/area/critical count), NOT a '
                               'certified rating',
              'model': 'sandbox-diffusive-screening-v2 (D8 channel-conditioned; NOT hydrodynamics)',
              'peak_discharge_m3s': 1533.6,
              'time_to_peak_min': 11.0,
              'hydrograph_volume_m3': 2000000.0}},
 {'id': '3e44fd8a-f466-4c0d-a881-2a633b04ae01',
  'run_kind': 'impact',
  'dam_id': 'd4',
  'dam_name': 'Fake Dam',
  'case': 'worst',
  'mode': 'REAL COMPUTED SIMULATION (screening model) — impact figures are modelled estimates',
  'engine': 'sandbox-diffusive-screening-v1',
  'created_at': '2026-09-26T08:43:19Z',
  'created_ts': 1790412199.2954059,
  'grids_present': False,
  'scenario': {'dam_id': 'd4',
               'label': 'worst',
               'reservoir_level_m': 71.25,
               'breach_location': 'dam',
               'breach_width_m': 200.0,
               'breach_depth_m': 45.0,
               'breach_severity': 'full',
               'initial_release_m3': 120000000.0,
               'roughness': 0.03,
               'rainfall_factor': 2.5,
               'duration_min': 180.0,
               'timestep_s': 60.0,
               'seed': 7,
               'breach_formation_min': None},
  'summary': {'overall_risk': 'LOW',
              'flooded_area_km2': 10.26,
              'settlements_assessed': 1,
              'settlements_inundated': 0,
              'settlements_at_risk': 0,
              'settlements_high_or_extreme': 0,
              'critical_assets_exposed': 0,
              'priority_counts': {'LOW': 1, 'MEDIUM': 0, 'HIGH': 0, 'CRITICAL': 0},
              'population_exposed': {'low': 0,
                                     'mid': 0,
                                     'high': 0,
                                     'basis': 'modelled',
                                     'basis_note': 'sum of per-settlement exposure (spread already '
                                                   'applied)'},
              'population_displaced': {'low': 0, 'mid': 0, 'high': 0, 'basis': 'modelled'},
              'people_protected': {'low': 0, 'mid': 0, 'high': 0},
              'damage': {'low_inr': 23841675,
                         'mid_inr': 36679500,
                         'high_inr': 49517325,
                         'basis': 'modelled',
                         'basis_note': 'sum of per-settlement loss + assumed agricultural share of '
                                       'the footprint'},
              'damage_breakdown': {'residential_inr': 0,
                                   'commercial_inr': 0,
                                   'infrastructure_inr': 0,
                                   'agriculture_inr': 36679500},
              'avoided': {'low_inr': 0,
                          'mid_inr': 0,
                          'high_inr': 0,
                          'basis': 'modelled',
                          'basis_note': 'estimated potential saving — early action reduces, never '
                                        'eliminates, damage'},
              'residual_damage': {'low_inr': 23841675, 'mid_inr': 36679500, 'high_inr': 49517325},
              'agriculture': {'low_inr': 23841675,
                              'mid_inr': 36679500,
                              'high_inr': 49517325,
                              'basis': 'modelled',
                              'basis_note': '5.643 km² of the modelled inundation footprint × 55% '
                                            'assumed cropland/pasture share × ₹65,000/ha',
                              'area_km2': 5.643},
              'peak_depth_m': 218.79,
              'earliest_arrival_min': None}}]

ALERT_DRAFT_ROWS = [{'id': 'a0bedc5c5bbd',
  'sim_run_id': '8f9faf31-009e-463d-a0c5-fec228f9097c',
  'scenario_id': None,
  'content': '[WARNING] Tehri Dam — modelled flood scenario (likely case).\n'
             'Screening-model estimate: inundated area 16.333 km², peak water depth — m. 0 '
             'settlement(s) inundated, 0 more at risk. Population potentially exposed: —–—. '
             'Earliest modelled arrival: not resolved. Figures are modelled screening estimates, '
             'not forecasts — verify on the ground. Source: run 8f9faf31.',
  'language': 'en',
  'severity': 'warning',
  'approved_by': 'Dev Operator',
  'dispatched_at': '2026-09-26T08:40:18Z',
  'created_at': '2026-09-26T08:21:13Z',
  'store': 'ledger',
  'dam_id': 'd4',
  'dam_name': 'Tehri Dam',
  'approved_by_id': '00000000-0000-0000-0000-000000000001',
  'approved_at': '2026-09-26T08:39:26Z'},
 {'id': 'd02ee1f93e64',
  'sim_run_id': '8f9faf31-009e-463d-a0c5-fec228f9097c',
  'scenario_id': None,
  'content': '[WARNING] Tehri Dam — modelled flood scenario (likely case).\n'
             'Screening-model estimate: inundated area 16.333 km², peak water depth 43.34 m. 7 of '
             '200 mapped assets fall in the modelled high-impact zone. Earliest modelled arrival: '
             'T+0.0 min. Figures are modelled screening estimates, not forecasts — verify on the '
             'ground. Source: run 8f9faf31.',
  'language': 'en',
  'severity': 'warning',
  'approved_by': 'Dev Operator',
  'dispatched_at': '2026-09-26T08:26:51Z',
  'created_at': '2026-09-26T08:26:35Z',
  'store': 'ledger',
  'dam_id': 'd4',
  'dam_name': 'Tehri Dam',
  'approved_by_id': '00000000-0000-0000-0000-000000000001',
  'approved_at': '2026-09-26T08:26:51Z'},
 {'id': '060624501683',
  'sim_run_id': '141fff13-e31c-4711-9931-c5a5d527d56a',
  'scenario_id': None,
  'content': '[WARNING] Idukki Dam — modelled flood scenario (test case).\n'
             'Screening-model estimate: inundated area 2.861 km², peak water depth 4.15 m. 0 of '
             '146 mapped assets fall in the modelled high-impact zone. Figures are modelled '
             'screening estimates, not forecasts — verify on the ground. Source: run 141fff13.',
  'language': 'en',
  'severity': 'warning',
  'approved_by': 'DamSafe Administrator',
  'dispatched_at': '2026-09-27T06:24:23Z',
  'created_at': '2026-09-26T08:38:49Z',
  'store': 'ledger',
  'dam_id': 'd52',
  'dam_name': 'Idukki Dam',
  'approved_by_id': 'd8fc278fd1aa',
  'approved_at': '2026-09-27T06:24:21Z'},
 {'id': 'be9379ec0dbd',
  'sim_run_id': '3c337931-249c-405d-8c6d-5b37a48b6dc3',
  'scenario_id': None,
  'content': '[WARNING] Tehri Dam — modelled flood scenario (test case).\n'
             'Screening-model estimate: inundated area 5.386 km², peak water depth 4.69 m. 2 of '
             '200 mapped assets fall in the modelled high-impact zone. Earliest modelled arrival: '
             'T+0.0 min. Figures are modelled screening estimates, not forecasts — verify on the '
             'ground. Source: run 3c337931.',
  'language': 'en',
  'severity': 'warning',
  'approved_by': None,
  'dispatched_at': None,
  'created_at': '2026-09-27T06:24:16Z',
  'store': 'ledger',
  'dam_id': 'd4',
  'dam_name': 'Tehri Dam'}]

USER_ROWS = []


def seed_demo_stores() -> dict:
    """Populate ONLY-EMPTY stores from the embedded snapshot (idempotent)."""
    import json
    from pathlib import Path

    data_dir = Path(__file__).resolve().parent.parent / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    applied = {}

    stores = (
        (data_dir / "run_ledger.json", RUN_LEDGER_ROWS, "runs"),
        (data_dir / "alert_drafts.json", ALERT_DRAFT_ROWS, "alerts"),
        (data_dir / "users.json", USER_ROWS, "users"),
    )
    for path, rows, label in stores:
        if path.exists() and path.read_text(encoding="utf-8").strip():
            applied[label] = "already-populated"
            continue
        if rows:
            path.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")
            applied[label] = f"seeded-{len(rows)}-rows"
        else:
            applied[label] = "snapshot-empty"
    return applied
